language: python
python:
  - 2.6
  - 2.7
  - 3.2
install:
  - pip install --use-mirrors behave coverage git+https://github.com/garybernhardt/expecter nose2 nose2_cov
  - pip install --use-mirrors .
script:
  - nose2 -v tests
  - behave tests/features
branches:
  except:
    - /^play\/.*$/
